version: ${DOCKER_COMPOSE_YML_VERSION}

services:
  proxy:
    image: nginxproxy/nginx-proxy:1.0.0
    container_name: ${APP_NAME_INTERNAL}_proxy
    volumes:
      # Nginx configuration
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${APP_PATH_ROOT}proxy/certs:/etc/nginx/certs:ro
      - ${APP_PATH_ROOT}proxy/vhost.d:/etc/nginx/vhost.d
      - ${APP_PATH_ROOT}proxy/html:/usr/share/nginx/html
      - ${APP_PATH_ROOT}proxy/logs:/var/log/nginx
      - ${APP_PATH_ROOT}proxy/wex.conf:/etc/nginx/conf.d/wex.conf
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: nginx_proxy
    privileged: true
    extends:
        file: ${WEX_COMPOSE_YML_DEFAULT}
        service: default
  certs:
    image: nginxproxy/acme-companion:2.2.1
    container_name: ${APP_NAME_INTERNAL}_certs
    volumes:
      - ${APP_PATH_ROOT}proxy/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - ${APP_NAME}_proxy
    extends:
        file: ${WEX_COMPOSE_YML_DEFAULT}
        service: default
