version: '3'

services:
  proxy:
    image: nginxproxy/nginx-proxy:1.0.0
    container_name: ${APP_NAME_INTERNAL}
    volumes:
      # Nginx configuration
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${APP_PATH_ROOT}proxy/certs:/etc/nginx/certs:ro
      - ${APP_PATH_ROOT}proxy/vhost.d:/etc/nginx/vhost.d
      - ${APP_PATH_ROOT}proxy/html:/usr/share/nginx/html
      - ${APP_PATH_ROOT}proxy/logs:/var/log/nginx
      - ${APP_PATH_ROOT}proxy/wex.conf:/etc/nginx/conf.d/wex.conf
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: nginx_proxy
    restart: always
    privileged: true
    networks:
      - wex_net

  certs:
    image: nginxproxy/acme-companion:2.2.1
    container_name: ${APP_NAME_INTERNAL}_certs
    volumes:
      - ${APP_PATH_ROOT}proxy/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

# TODO Run it in production only, if expected by at least one app (or move to proper ftp)
#  ftp:
#    image: wexample/ftp
#    container_name: ${APP_NAME_INTERNAL}_ftp
#    environment:
#      - PUBLICHOST=${SERVER_IP}
#      - PORTS_RANGE=30000:30059
#    volumes:
#      # Share all sites
#      - /var/www:/var/www
#      # Store passwords in the same place
#      - ${APP_PATH_ROOT}proxy/ftp/passwd:/etc/pure-ftpd/passwd
#    networks:
#      - wex_net
#    ports:
#      - "21:21"
#      - "30000-30059:30000-30059"
