version: '3'

services:
  proxy:
    image: nginxproxy/nginx-proxy:1.0.0
    container_name: ${APP_NAME_INTERNAL}
    volumes:
      # Nginx configuration
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${APP_PATH_ROOT}proxy/certs:/etc/nginx/certs:ro
      - ${APP_PATH_ROOT}proxy/vhost.d:/etc/nginx/vhost.d
      - ${APP_PATH_ROOT}proxy/html:/usr/share/nginx/html
      - ${APP_PATH_ROOT}proxy/logs:/var/log/nginx
      - ${APP_PATH_ROOT}proxy/wex.conf:/etc/nginx/conf.d/wex.conf
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: nginx_proxy
    restart: always
    privileged: true
    networks:
      - wex_net

